### ISSUE TITLE
Kerberos is not working to authenticate Print@UCL

### ISSUE THREAD

**Issue by galaxyeden** [UCL/Mac-Support-Resources#1]
Kerberos is not working to authenticate Print@UCL since the name change to print.ucl.ac.uk. Also worth noting that the printers are no longer published. Both issues have been raised in RemedyForce, IN02510633

**Comment by AllieTheUnicorn** [comment]
Also worth noting that the printers are no longer published. Both issues have been raised in RemedyForce, IN02510633

**Comment by owainkenwayucl** [comment]
I would strongly recommend not connecting via SMB to print@ucl, instead connecting over LPD.

This works better on Linux (me), Mac (colleagues) and Windows (colleagues) and completely side-steps all authentication issues.  The only snag is that if your userid on your machine is *not* your UCL userid it can get a bit complicated to set up (although not impossible).

I don't have Mac instructions to hand, but I wrote up the Linux instructions some time ago and they are on the internal UCL wiki here: https://wiki.ucl.ac.uk/display/~uccaoke/Accessing+PrintATUCL+through+LPD+on+Linux

_(oh and see the comments for more details on what to do if userids don't match and updates to the URI for the printer as ISD keeps changing it)._

**Comment by galaxyeden** [comment]
Hi Owain,

You're not the first to suggest this. I do wonder, will unauthenticated printing be supported long-term by UCL? Setting up the queue should actually be pretty easy, as I'm creating a quick installer, and prompting for userID is trivial. It's more the support aspect that has me hesitant to go down the LPD route. Thank you in advance for your thoughts on this.

Kind regards,

Alex Uhde

**Comment by owainkenwayucl** [comment]
They explicitly allow unauthenticated printing sent by email which is trivial to spoof, and when I last asked the print@UCL people (this comes up a lot on the IT managers list a lot wrt linux support on multi-user machines) they had no intention of turning it off.  (My plan is to get enough people to use it that if they do turn it off there will be a minor outcry).

It's still sort of authenticated, as you still need your ID card to collect the jobs, which is what they care about from a security + billing perspective.

**Comment by galaxyeden** [comment]
That sounds like a plan. I'll do some more testing on this option as well then, thank you.

**Comment by galaxyeden** [comment]
This has been fixed by the WIS team.
