### ISSUE TITLE
MacOS Mail not working

### ISSUE THREAD

**Issue by yusahhamuth** [UCL/Mac-Support-Resources#3]
Mail in the following versions are known not to be working: Yosemite, El Capitan. Upgrade to Sierra fixes problem.

**Comment by galaxyeden** [comment]
Are these users using Exchange or IMAP to connect?

**Comment by yusahhamuth** [comment]
Exchange, Alex

2 are sorted, 1 still thinking of upgrade from Yosemite

Regards


On 3 Aug 2017, at 10:19, Allie Uhde <notifications@github.com<mailto:notifications@github.com>> wrote:


Are these users using Exchange or IMAP to connect?

**Comment by galaxyeden** [comment]
Can you confirm that you've had no users on Sierra with this issue? There are a lot of reports on the Mac User Group mailing list, and OS version isn't mentioned on most of them - but I'd find it surprising if such a large proportion of that list is both using an old OS release and using Mail. I've asked them to come here and add details of their setup, so hopefully tomorrow we'll have some more insight. I'm also trying to get someone who can spare a half hour to show me the issue in person tomorrow.

**Comment by yusahhamuth** [comment]
Yes, so far no one with Sierra has reported Mail not working. 2 upgraded users have reported that Mail is ok now.

Yusah.


On 3 Aug 2017, at 23:11, Allie Uhde <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you confirm that you've had no users on Sierra with this issue? There are a lot of reports on the Mac User Group mailing list, and OS version isn't mentioned on most of them - but I'd find it surprising if such a large proportion of that list is both using an old OS release and using Mail. I've asked them to come here and add details of their setup, so hopefully tomorrow we'll have some more insight. I'm also trying to get someone who can spare a half hour to show me the issue in person tomorrow.

**Comment by alex-olayacastro** [comment]
Hello, my MAC Mail application also stopped downloading emails on the Inbox. It still downloads to the sent mail folder the emails I sent from my Iphone. I have an OS X 10.9.5 (Build 13F1911) and I am noticing a Yammer Root folder which was not there before.

**Comment by galaxyeden** [comment]
Hi @alex-olayacastro - would you be willing to show this to me this afternoon? If you're in the Bloomsbury Campus area, I'd really like to see an affected machine for a few minutes hands-on.

**Comment by alex-olayacastro** [comment]
Hi @AllieTheUnicorn, yes, I am based in Physics and I am happry to go your way. I am free at around 3:15 pm. Where shall I meet you?

**Comment by galaxyeden** [comment]
@alex-olayacastro I'll send you my mobile number off GitHub so you can give me a ring and see where I am when you're free.

**Comment by galaxyeden** [comment]
This has been acknowledged by Microsoft to be a bug in their system, and they're working on a fix. As a workaround, please use OWA, Outlook, another client or upgrade to Sierra until Microsoft has resolved this.
